receivers:
  mongodb:
    connection_string: "mongodb://sincrock-mongo_server_1:27017/?directConnection=true"
    collection_interval: 10s

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  otlp:
    endpoint: "sincrock-grafana-otel-lgtm_server_1:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [mongodb]
      processors: [batch]
      exporters: [otlp]
