services:
  app_proxy:
    environment:
      APP_HOST: sincrock-waha_server_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: “false”
    container_name: sincrock-waha_app_proxy_1

  server:
    image: devlikeapro/waha:gows-arm-2026.8.1@sha256:123e2220ce3ac3ca83e0691ca6df0b3e655e37e6e6ceab596c8a4bb3a6d69be7
    container_name: sincrock-waha_server_1
    restart: on-failure
    user: "0:0"
    env_file:
      - ${APP_DATA_DIR}/.env
    volumes:
      - ${APP_DATA_DIR}/.env:/app/.env
      - ${APP_DATA_DIR}/data/sessions:/app/.sessions
      - ${APP_DATA_DIR}/data/media:/app/.media