version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sincrock-clamav_server_1
      APP_PORT: 3310

  server:
    image: clamav/clamav-debian:latest
    restart: on-failure
    user: "root"
    volumes:
      - "${UMBREL_ROOT}/home/Downloads:/data/downloads:ro"
      - "${UMBREL_ROOT}/home/Documents:/data/documents:ro"
      - "${UMBREL_ROOT}/home/Photos:/data/photos:ro"
      - "${UMBREL_ROOT}/home/Videos:/data/videos:ro"
    entrypoint: ["sh", "-c", "freshclam && tail -f /dev/null"]