version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: server
      APP_PORT: 3310

  server:
    image: clamav/clamav-debian:latest
    restart: on-failure
    user: "root"
    volumes:
      - "${UMBREL_ROOT}/home/Downloads:/data/downloads:ro"
      - "${UMBREL_ROOT}/home/Documents:/data/documents:ro"
      - "${UMBREL_ROOT}/home/Photos:/data/photos:ro"
      - "${UMBREL_ROOT}/home/Videos:/data/videos:ro"
    healthcheck:
      test: ["CMD", "clamdscan", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s